create DATABASE todoDB

create TABLE TODO_FOLDERS
(
    ID int IDENTITY(1,1),
    NAME VARCHAR(max) not null,
    DESCRIPTION VARCHAR(MAX) null,
    CREATED_ON DATETIME not null,
    MODIFIED_ON DATETIME not null,
    CONSTRAINT PK_FOLDER_ID PRIMARY KEY (ID)
)

create TABLE TODOS
(
    ID int IDENTITY(1,1),
    NAME VARCHAR(max) not null,
    DESCRIPTION VARCHAR(MAX) null,
    CREATED_ON DATETIME not null,
    MODIFIED_ON DATETIME not null,
    FOLDER_ID int not null,
    CONSTRAINT PK_TODO_ID PRIMARY KEY (ID),
    CONSTRAINT FK_TODO_FOLDER_ID FOREIGN KEY (FOLDER_ID) references TODO_FOLDERS(ID) ON DELETE cascade
)